const KEY="ibn_products", OKEY="ibn_orders", SKEY="ibn_settings";
const defaults=[
{id:1,name:"شنطة مدرسية ولادي",price:450,oldPrice:500,category:"شنط مدارس",stock:20,emoji:"🎒",desc:"شنطة مدرسية عملية."},
{id:2,name:"شنطة سفر كبيرة",price:850,oldPrice:950,category:"شنط سفر",stock:10,emoji:"🧳",desc:"شنطة سفر واسعة."},
{id:3,name:"محفظة جلد رجالي",price:250,oldPrice:300,category:"محافظ",stock:25,emoji:"👛",desc:"محفظة أنيقة."},
{id:5,name:"ناموسية أطفال",price:350,oldPrice:400,category:"ناموسيات أطفال",stock:15,emoji:"🛏️",desc:"ناموسية للأطفال."},
{id:6,name:"شمسية قماش",price:120,oldPrice:150,category:"شمسيات",stock:30,emoji:"☂️",desc:"شمسية عملية."}];
function get(k,d){try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}}
function set(k,v){localStorage.setItem(k,JSON.stringify(v))}
if(!localStorage.getItem(KEY))set(KEY,defaults);
if(!localStorage.getItem(SKEY))set(SKEY,{storeName:"ابن الملك",phone:"01285151156",whatsapp:"201285151156",shipping:50,banner:"جودة عالية بأسعار مميزة"});
function products(){return get(KEY,[])} function cart(){return get("ibn_cart",[])}
function saveCart(c){set("ibn_cart",c);document.querySelector("#count")&&(document.querySelector("#count").textContent=c.reduce((a,x)=>a+x.qty,0))}
function renderHome(){let ps=products(), q=(document.querySelector("#search")?.value||"").toLowerCase();document.querySelector("#grid").innerHTML=ps.filter(p=>!q||p.name.toLowerCase().includes(q)).map(p=>`<article class="card"><div class="pic">${p.image?`<img src="${p.image}">`:p.emoji||"📦"}</div><h3>${p.name}</h3><small>${p.category}</small><div class="price">${p.price} جنيه ${p.oldPrice?`<del><small>${p.oldPrice}</small></del>`:""}</div><button class="btn buy" onclick="add(${p.id})">أضف للسلة</button></article>`).join("");document.querySelector("#cats").innerHTML=["شنط مدارس","شنط سفر","شنط حريمي","شنط بناتي","محافظ","ناموسيات أطفال","شمسيات"].map(c=>`<a class="cat" href="#products" onclick="filterCat('${c}')">🛍️<br>${c}</a>`).join("");let s=get(SKEY,{});document.querySelector("#contact").textContent=s.phone?`للطلب والاستفسار: ${s.phone}`:"للطلب والاستفسار: أضف رقمك من لوحة التحكم";saveCart(cart())}
function filterCat(c){document.querySelector("#search").value=c;renderHome()}
function add(id){let c=cart(),i=c.findIndex(x=>x.id===id);i>=0?c[i].qty++:c.push({id,qty:1});saveCart(c);alert("تمت إضافة المنتج للسلة")}
function renderCart(){let c=cart(),ps=products(), box=document.querySelector("#cart");if(!box)return;let total=0;box.innerHTML=c.map(x=>{let p=ps.find(y=>y.id===x.id);if(!p)return"";total+=p.price*x.qty;return `<div class="card"><b>${p.name}</b> — ${x.qty} × ${p.price} = ${p.price*x.qty} جنيه <button onclick="removeItem(${p.id})">حذف</button></div>`}).join("")||"<p>السلة فارغة.</p>";box.innerHTML+=`<h2>الإجمالي: ${total} جنيه</h2>`;document.querySelector("#orderForm")?.addEventListener("submit",submitOrder,{once:true})}
function removeItem(id){saveCart(cart().filter(x=>x.id!==id));renderCart()}
function submitOrder(e){e.preventDefault();let f=new FormData(e.target), order={id:Date.now(),name:f.get("name"),phone:f.get("phone"),gov:f.get("gov"),address:f.get("address"),items:cart(),date:new Date().toLocaleString("ar-EG"),status:"جديد"};let os=get(OKEY,[]);os.unshift(order);set(OKEY,os);set("ibn_cart",[]);alert("تم تسجيل الطلب بنجاح");location.href="index.html"}
function renderAdmin(){let form=document.querySelector("#productForm");form.addEventListener("submit",saveProduct);drawAdminProducts();drawOrders();let s=get(SKEY,{}),sf=document.querySelector("#settingsForm");Object.keys(s).forEach(k=>{if(sf.elements[k])sf.elements[k].value=s[k]??""});sf.addEventListener("submit",e=>{e.preventDefault();let o={};for(let x of new FormData(sf).entries())o[x[0]]=x[1];o.shipping=+o.shipping||0;set(SKEY,o);alert("تم حفظ الإعدادات")})}
function saveProduct(e){e.preventDefault();let f=e.target, p=products(), id=+f.id.value||Date.now();let finish=image=>{let x={id,name:f.name.value,price:+f.price.value,oldPrice:+f.oldPrice.value||0,category:f.category.value,stock:+f.stock.value||0,desc:f.desc.value,emoji:"📦"};if(image)x.image=image;let i=p.findIndex(y=>y.id===id);i>=0?p[i]=Object.assign(p[i],x):p.push(x);set(KEY,p);f.reset();f.id.value="";drawAdminProducts();alert("تم حفظ المنتج")};if(f.image.files[0]){let r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(f.image.files[0])}else finish(null)}
function drawAdminProducts(){let box=document.querySelector("#adminProducts");if(!box)return;box.innerHTML=products().map(p=>`<div class="admin-item"><span><b>${p.name}</b><br>${p.price} جنيه — مخزون ${p.stock}</span><span><button onclick="editP(${p.id})">تعديل</button> <button class="danger" onclick="delP(${p.id})">حذف</button></span></div>`).join("")}
function editP(id){let p=products().find(x=>x.id===id),f=document.querySelector("#productForm");f.id.value=p.id;["name","price","oldPrice","category","stock","desc"].forEach(k=>f[k].value=p[k]??"");scrollTo(0,0)}
function delP(id){if(confirm("حذف المنتج؟")){set(KEY,products().filter(p=>p.id!==id));drawAdminProducts()}}
function drawOrders(){let b=document.querySelector("#orders");if(!b)return;let os=get(OKEY,[]);b.innerHTML=os.map(o=>`<div class="card"><b>طلب #${o.id}</b><p>${o.name} — ${o.phone}<br>${o.gov} — ${o.address}</p><small>${o.date} — ${o.status}</small></div>`).join("")||"<p>لا توجد طلبات.</p>"}
function showTab(t){["products","orders","settings"].forEach(x=>document.querySelector("#"+x+"Tab").classList.toggle("hidden",x!==t))}
if(document.querySelector("#grid")){renderHome();document.querySelector("#search").addEventListener("input",renderHome)}
